apiVersion: v1
kind: Pod
metadata:
  name: backend
  labels:
    course: mundose
    app: backend
spec:
  containers:
    - name: backend
      image: docker.io/elviejo1/mundose-backend:latest
      ports:
        - name: http
          containerPort: 8080
          protocol: TCP

